name: Build Openwrt
on:
    push:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: MasterworksIO/action-local-cache@2
              name: "Load Toolchain Cache"
              with:
                path: './staging_dir'
                key: 'staging_toolchain'
            - uses: MasterworksIO/action-local-cache@2
              name: "Load Feeds Cache"
              with:
                path: './feeds'
                key: 'feeds'
            - name: 'Update Feeds'
              run: ./scripts/feeds update -a && ./scripts/feeds install -a
            - name: "Copy config"
              run: cp 7800.config .config && make defconfig && make oldconfig
            - name: "Build"
              run: make -j2 || make V=s
          - name: Upload buildinfo
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
